name: fit_io
description: "Fit.io — Offline-first habit tracker for students."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.2.2
  path_provider: ^2.0.11
  path: ^1.8.2
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Allows SQLite unit tests to run on desktop/CI without a device
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true
